### ISSUE TITLE
运行app.py会出错，请问要怎么解决

### ISSUE THREAD

**Issue by iMechainc** [HKoon/ChatTTS-OpenVoice#7]
运行环境：64位win10，python3.10
运行app.py会出现以下错误：
Traceback (most recent call last):
  File "E:\AI\ChatTTS-OpenVoice\app.py", line 12, in <module>
    from OpenVoice import se_extractor
ImportError: cannot import name 'se_extractor' from 'OpenVoice' (unknown location)

**Comment by yipeng7816** [comment]
![image](https://github.com/user-attachments/assets/712c06b0-5dc9-4b80-a1a6-a2496a96a55f)

**Comment by hemidio** [comment]
1. clone code from https://github.com/myshell-ai/OpenVoice/tree/main, 
2. replace OpenVoice folder with the inner openvoice folder of new download project
3. replace all 'openvoice' with 'OpenVoice'  in import code
4. download checkpoint file from https://myshell-public-repo-host.s3.amazonaws.com/openvoice/checkpoints_v2_0417.zip
5. unzip zip file, rename checkpoints_v2 to checkpoints and copy it to \ChatTTS-OpenVoice\OpenVoice\

**Comment by a289672082** [comment]
做py的都那么随意的吗 这么大一个问题都无视

**Comment by HKoon** [comment]
> 做py的都那么随意的吗 这么大一个问题都无视

现在这个是线上正在跑的代码，需要自己下载checkpoint到OpenVoice的文件夹里

**Comment by HKoon** [comment]
所以是验证过的，报错是没有下载好东西

**Comment by HKoon** [comment]
> 做py的都那么随意的吗 这么大一个问题都无视,建议这个开源库直接删库,浪费公共资源

白嫖还打包呗

**Comment by HKoon** [comment]
> 1. clone code from https://github.com/myshell-ai/OpenVoice/tree/main,
> 2. replace OpenVoice folder with the inner openvoice folder of new download project
> 3. replace all 'openvoice' with 'OpenVoice'  in import code
> 4. download checkpoint file from https://myshell-public-repo-host.s3.amazonaws.com/openvoice/checkpoints_v2_0417.zip
> 5. unzip zip file, rename checkpoints_v2 to checkpoints and copy it to \ChatTTS-OpenVoice\OpenVoice\

Thank you for the additional information.

**Comment by HKoon** [comment]
> ![image](https://private-user-images.githubusercontent.com/29189137/365067030-712c06b0-5dc9-4b80-a1a6-a2496a96a55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODUzMDIsIm5iZiI6MTcyODQ4NTAwMiwicGF0aCI6Ii8yOTE4OTEzNy8zNjUwNjcwMzAtNzEyYzA2YjAtNWRjOS00YjgwLWExYTYtYTI0OTZhOTZhNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE0NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMzZmYzZiNzZhNGI1M2RhNWRjYzlmNWE4MmVlNmVjOTkzOGVmZTQyYmRjYjdlNzkzMTYyYzA0NDAxY2ZjMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bgaH5g_Z7jDw3UHAQB32L1149bVfI3pq-V6Hm60D5LM)

感谢补充，确实是规整代码过程中遗漏了。

**Comment by HKoon** [comment]
已修复

**Comment by HKoon** [comment]
> 做py的都那么随意的吗 这么大一个问题都无视,建议这个开源库直接删库,浪费公共资源

我不删，我必须留下这个库以及你这个评论警醒我自己。世界上是有活雷锋的，也有白嫖完还愿意回过头鞭策别人进度的大善人。

**Comment by ssbeaut** [comment]
> ![图像](https://private-user-images.githubusercontent.com/29189137/365067030-712c06b0-5dc9-4b80-a1a6-a2496a96a55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjAxNjYsIm5iZiI6MTczMDM1OTg2NiwicGF0aCI6Ii8yOTE4OTEzNy8zNjUwNjcwMzAtNzEyYzA2YjAtNWRjOS00YjgwLWExYTYtYTI0OTZhOTZhNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA3MzEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxN2M1ZmQxNDNjZjliMGZlZmIwZjFmZWRhMDBjZTczMjZhNzcyZGU3MjA0NGIxMGYyNjJkM2EwMGIzOWY4MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CKQt_9O42cYzlRLshUeNi_Mb3Wrv3_v8-FSBOcmILRo)

版主他写错了，你要将你ChatTTS-OpenVoice 文件里的OpenVoice改成小写openvoice   ，APP代码中的所有“OpenVoice”替换为“openvoice”，将APP第一行 #import spaces   禁掉。就可以了

**Comment by ssbeaut** [comment]
> ## 多谢,我这边无法解决,已在寻找替代品。
> Traceback (most recent call last): File "E:\OpenVoice\ChatTTS-OpenVoice\app.py", line 13, in from OpenVoice.api import ToneColorConverter File "E:\OpenVoice\ChatTTS-OpenVoice\OpenVoice\api.py", line 11, in from .utils.models import SynthesizerTrn File "E:\OpenVoice\ChatTTS-OpenVoice\OpenVoice\utils\models.py", line 13, in from .utils.commons import init_weights, get_padding ModuleNotFoundError: No module named 'OpenVoice.utils.utils.commons'; 'OpenVoice.utils.utils' is not a package

![image](https://github.com/user-attachments/assets/62089aab-2546-47ec-ac22-d87bb9d67c8a)

**Comment by ssbeaut** [comment]
> > ## 多谢，我努力解决问题，已在寻找替代品。
> > 回溯（最近一次调用最后一次）：文件“E:\OpenVoice\ChatTTS-OpenVoice\app.py”，第 13 行，来自 OpenVoice.api 导入 ToneColorConverter 文件“E:\OpenVoice\ChatTTS-OpenVoice\OpenVoice\api.py”，第 11 行，来自 .utils.models 导入 SynthesizerTrn 文件“E:\OpenVoice\ChatTTS-OpenVoice\OpenVoice\utils\models.py”，第 13 行，来自 .utils.commons 导入 init_weights、get_padding ModuleNotFoundError：没有名为“OpenVoice.utils.utils.commons”的模块；“OpenVoice.utils.utils”不是包
> 
> ![图像](https://private-user-images.githubusercontent.com/183329398/381865609-62089aab-2546-47ec-ac22-d87bb9d67c8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjE3ODcsIm5iZiI6MTczMDM2MTQ4NywicGF0aCI6Ii8xODMzMjkzOTgvMzgxODY1NjA5LTYyMDg5YWFiLTI1NDYtNDdlYy1hYzIyLWQ4N2JiOWQ2N2M4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNzU4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzY5NDBlYmQxYjQ2OTFhMWM2MmU2YzczODYzOWE4ZGE1NzJiMTNkZWRjZmEyYWViNGYxNDY4NzM5ZDhmMzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RuvzUkls2XecYnnAmyt6TqyQOvqjEDeSVt8nGo1qoNg)


![image](https://github.com/user-attachments/assets/42269dda-08b9-41b0-aa57-31debcaf2b80)
APP.py代码，里的方法一@GPU也要去掉下不然会报错，

**Comment by HKoon** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/29189137/365067030-712c06b0-5dc9-4b80-a1a6-a2496a96a55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjAxNjYsIm5iZiI6MTczMDM1OTg2NiwicGF0aCI6Ii8yOTE4OTEzNy8zNjUwNjcwMzAtNzEyYzA2YjAtNWRjOS00YjgwLWExYTYtYTI0OTZhOTZhNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA3MzEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxN2M1ZmQxNDNjZjliMGZlZmIwZjFmZWRhMDBjZTczMjZhNzcyZGU3MjA0NGIxMGYyNjJkM2EwMGIzOWY4MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CKQt_9O42cYzlRLshUeNi_Mb3Wrv3_v8-FSBOcmILRo)
> 
> 版主他写错了，你要将你ChatTTS-OpenVoice 文件里的OpenVoice改成小写openvoice ，APP代码中的所有“OpenVoice”替换为“openvoice”，将APP第一行 #import spaces 禁掉。就可以了

如果要改为小写，记得将文件夹名字改成小写

**Comment by 2063657** [comment]
这项目真乱啊，垃圾
