### ISSUE TITLE
ModuleNotFoundError: No module named 'OpenVoice.utils.utils.commons'; 'OpenVoice.utils.utils' is not a package

### ISSUE THREAD

**Issue by xy3xy3** [HKoon/ChatTTS-OpenVoice#9]
```
(chattts) root@autodl-container-fa5b45ae8c-3f5f19fe:~/ChatTTS-OpenVoice# python app.py
Traceback (most recent call last):
  File "/root/ChatTTS-OpenVoice/app.py", line 15, in <module>
    from OpenVoice.api import ToneColorConverter
  File "/root/ChatTTS-OpenVoice/OpenVoice/api.py", line 11, in <module>
    from .utils.models import SynthesizerTrn
  File "/root/ChatTTS-OpenVoice/OpenVoice/utils/models.py", line 13, in <module>
    from .utils.commons import init_weights, get_padding
ModuleNotFoundError: No module named 'OpenVoice.utils.utils.commons'; 'OpenVoice.utils.utils' is not a package
```

运行提示这个，好像,utils了两次

**Comment by HKoon** [comment]
这个提示就是缺了相对应的模块，需要检查一下相应位置的py文件是否存在并命名一致

**Comment by yinpeilin** [comment]
just change the 
`from .utils.commons import init_weights, get_padding `
to 
``from .commons import init_weights, get_padding ``
can fix the bug
